name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  numOctocats:
    description: 'Number of Octocats'
    required: true
    default: '1'
  octocatEyeColor:
    description: 'Eye color of the Octocats'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
  newoutpur: # id of output
    description: 'The new output'

runs:
  using: 'node12'
  main: 'index.js'